# -*- coding: utf-8 -*-

"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.8.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import logging
import os
# from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP


# logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(lineno)d ： %(message)s')
# logger = logging.getLogger(__name__)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6h88(4m0rk&ub^^s0=%pv+tu#0%960xrg68*ats#tzvxwg&6a+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False


ALLOWED_HOSTS = ["*"]

AUTH_USER_MODEL = "new_users.CmsUser"

# Application definition

INSTALLED_APPS = (
    # 'corsheaders',
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls',
    'polls_2',
    'new_users',


)

# CORS_ORIGIN_WHITELIST = (
#       'http://localhost:63343',
# )


MIDDLEWARE_CLASSES = (
    # 'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 'polls.middleware.LoggingMiddleware',
)

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
             # '/Users/wangjinyu/PycharmProjects/django1.8_demo/templates',
             # Put strings here, like "/home/html/django_templates" or "C:/www/django/templates".
             # Always use forward slashes, even on Windows.
             # Don't forget to use absolute paths, not relative paths.
              os.path.join(BASE_DIR, 'templates').replace('\\', '/'),
         ],
        # "DIRS":[],
        'APP_DIRS': False,
        'OPTIONS': {
            'debug': DEBUG,
            'context_processors': [
                # 'django.core.context_processors.request',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                # List of callables that know how to import templates from various sources.
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'django.template.loaders.eggs.Loader',
            ]
        },
    },
]


# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'templates')],
#         #DIRS默认为空
#         # 'DIRS': [],
#         # 'APP_DIRS': True,
#         'APP_DIRS': False,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases



"""
python manage.py migrate 会在default中的空的mysql数据库中创建
auth_group、auth_user、django_migrations等10张table，
python manage.py createsuperuser生成的管理员用户数据会催到auth_user表中

"""


# DATABASE_ROUTERS = ['mysite.database_router.Router',]
DATABASES = {
    #mysql配置
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'demo',
        'USER': 'root',
        'PASSWORD': '124419',
        'HOST': '127.0.0.1',
        'PORT': '3306',

        #默认
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'demo2': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'demo2',
        'USER': 'root',
        'PASSWORD': '124419',
        'HOST': '127.0.0.1',
        'PORT': '3306',
}
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'
#默认时区
# TIME_ZONE = 'UTC'

#中国时区
TIME_ZONE = 'Asia/Shanghai'
TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

#默认为True
#USE_TZ = True
#改为False后mysql时区才与TIME_ZONE的设置同步
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT='/Users/wangjinyu/PycharmProjects/django1.8_demo/static'
STATICFILES_DIRS=('/Users/wangjinyu/PycharmProjects/django1.8_demo/static',)

# Django Suit configuration example



SUIT_CONFIG = {
    # header
    'ADMIN_NAME': 'Django Suit Demo',
    'HEADER_DATE_FORMAT': 'l, j---F Y',
    'HEADER_TIME_FORMAT': 'H:i',

    # 'HEADER_DATE_FORMAT': 'c',
    # 'HEADER_TIME_FORMAT': 'r',

    # forms
    'SHOW_REQUIRED_ASTERISK': True,  # Default True
    # 'CONFIRM_UNSAVED_CHANGES': True, # Default True

    # menu
    'SEARCH_URL': '/admin/auth/user/',
    'MENU_ICONS': {
       'sites': 'icon-leaf',
       'auth': 'icon-lock',
    },
    'MENU_OPEN_FIRST_CHILD': True, # Default True
    # 'MENU_EXCLUDE': ('auth.group',),
    'MENU': (
        # 'sites',
        {'app': 'auth', 'icon': 'icon-lock'},

        # {'app': 'auth', 'icon':'icon-lock', 'models': ('new_users' 'groups')},
        {'app': 'new_users', 'icon':'icon-lock'},
        {'app': 'polls', 'label': 'polls', 'icon': 'icon-file', 'models': (
            'Question','Choice',

        )},
        {'label': 'Settings', 'icon':'icon-cog', 'models': ('auth.user', 'auth.group')},
        {'label': 'Support', 'icon':'icon-question-sign', 'url': '/support/'},
    ),

    # misc
    'LIST_PER_PAGE': 1
}



# TEMPLATE_CONTEXT_PROCESSORS = TCP + (
#     'django.core.context_processors.request',
# )
logger=logging.getLogger('wang')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '%(asctime)s %(levelname)s [%(filename)s:%(lineno)d] -> %(message)s'
        },
    },
    'handlers': {
        'default': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['default'],
            'level': 'DEBUG',
        },
        'django.request': {
            'handlers': ['default'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}

CACHES = {
    # 'default': {
    #     'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    #     'OPTIONS': {
    #         'MAX_ENTRIES': 1000,
    #     }
    # },
    # 'redis': {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION':'redis://127.0.0.1:6379/0',
        # 'LOCATION': [ 'redis://127.0.0.1:3306/0', # '{url}{db}'.format(url=Const.LCX_REDIS_SG, db=6),]
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # 'PASSWORD': "124419",
        },
    },
}
